---
- name: setup bastion Host
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: import Bastion setup variables
      include_vars: vars/bastion_setup
    - name: import output & vpc setup variables
      include_vars: vars/output-vars

    - name: create ec2 key
      ec2_key:
        name: bastion-key
        region: "{{region}}"
      register: keyout
    - debug:
        var: keyout

    - name: save pvt key into file bastion.pem
      copy:
        content: "{{keyout.key.private_key}}"
        dest: "./bastion.pem"
        mode: 0600
      when: keyout.changed

